# Generated by Django 3.2.4 on 2023-08-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpositions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Medical', 'Medical'), ('Electrical', 'Electrical'), ('Electronics', 'Electronics'), ('BPO', 'BPO'), ('Construction Field', 'Construction Field'), ('Mechanical', 'Mechanical')], default='IT', max_length=50),
        ),
    ]
