# Generated by Django 3.2.4 on 2023-08-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpositions', '0003_alter_jobposition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='proceedings',
            field=models.TextField(default=''),
        ),
    ]
