# Generated by Django 3.2.4 on 2023-09-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpositions', '0004_jobposition_proceedings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Medical', 'Medical'), ('Electrical', 'Electrical'), ('Electronics', 'Electronics'), ('BPO', 'BPO'), ('Construction Field', 'Construction Field'), ('Mechanical', 'Mechanical'), ('Farming', 'Farming'), ('Sales', 'Sales')], default='IT', max_length=50),
        ),
    ]
