# Generated by Django 3.2.4 on 2023-12-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpositions', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('repassword', models.CharField(max_length=255)),
            ],
        ),
    ]
