# Generated by Django 3.2.4 on 2023-12-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpositions', '0007_institutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('institution_name', models.CharField(max_length=255)),
                ('offered_courses', models.TextField()),
                ('training_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('billing_date', models.DateField(auto_now_add=True)),
                ('billing_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
