# Generated by Django 3.2.4 on 2023-12-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpositions', '0008_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billing_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
