# Generated by Django 3.2.4 on 2023-12-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpositions', '0009_alter_billing_billing_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='institution_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/institution_logos/'),
        ),
    ]
