# Generated by Django 3.2.4 on 2023-12-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpositions', '0010_alter_billing_institution_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billing_date',
            field=models.CharField(max_length=255),
        ),
    ]
