# Generated by Django 3.2.4 on 2023-12-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpositions', '0011_alter_billing_billing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='logos/institution_logos/')),
                ('institution_name', models.CharField(max_length=255)),
                ('offered_courses', models.TextField()),
                ('training_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('billing_date', models.CharField(max_length=255)),
                ('billing_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='billing',
            name='address',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='email',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='institution_logo',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='offered_courses',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='training_type',
        ),
    ]
