# Generated by Django 3.2.4 on 2023-12-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpositions', '0012_auto_20231224_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
