# Generated by Django 3.2.4 on 2023-12-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpositions', '0013_billing_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='billing_cost',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='billing_date',
        ),
    ]
