# Generated by Django 4.2.8 on 2023-12-30 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobpositions', '0014_auto_20231228_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutor',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
