# Generated by Django 4.2.8 on 2023-12-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpositions', '0015_institutor_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutor',
            name='last_login',
        ),
    ]
